# Generated by Django 6.0.4 on 2026-05-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_insight_ai_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=models.CharField(default='post', max_length=10),
        ),
        migrations.AddField(
            model_name='content',
            name='file_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
