# Generated by Django 6.0.4 on 2026-05-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_content_content_type_content_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='insight',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='prediction',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
