# Generated by Django 6.0.4 on 2026-05-11 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, default='', max_length=100)),
                ('niche', models.CharField(choices=[('fitness', 'Fitness & Health'), ('tech', 'Technology'), ('food', 'Food & Cooking'), ('fashion', 'Fashion & Style'), ('education', 'Education'), ('business', 'Business & Entrepreneurship'), ('travel', 'Travel'), ('entertainment', 'Entertainment'), ('beauty', 'Beauty & Skincare'), ('other', 'Other')], default='other', max_length=50)),
                ('target_audience', models.CharField(choices=[('teens', 'Teens (13-17)'), ('young_adults', 'Young Adults (18-24)'), ('adults', 'Adults (25-34)'), ('professionals', 'Professionals (35+)'), ('general', 'General Audience')], default='general', max_length=50)),
                ('posting_goal', models.CharField(choices=[('grow_followers', 'Grow Followers'), ('increase_engagement', 'Increase Engagement'), ('promote_business', 'Promote Business'), ('build_brand', 'Build Personal Brand'), ('drive_sales', 'Drive Sales')], default='grow_followers', max_length=50)),
                ('onboarding_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
